# -*- coding: utf-8 -*-
"""Customer Churn & Lifetime Value

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjR0EEx9jeoImEGs4JCSvkIzk6dHRqmV

# Predicting Customer Churn & Lifetime Value using Machine Learning

**Business Overview**

A telecommunications company provides internet, phone, and streaming services to thousands of customers. Customer retention has become a critical business challenge as acquiring new customers is significantly more expensive than retaining existing ones.
The company has observed an increasing number of customers terminating their subscriptions (customer churn), resulting in revenue loss and increased acquisition costs.
To address this issue, the management team requires a data-driven analysis to identify the key factors contributing to customer churn and provide actionable recommendations to improve customer retention.

**Business Problem:**

The company currently lacks clear visibility into:
- Which customers are most likely to churn
- What customer characteristics contribute to churn
- Which services are associated with higher churn
- Which customer segments generate the highest revenue
- How contract type influences customer retention

**Business Objectives**

This project aims to:
- Analyze customer churn behavior
- Identify factors affecting churn
- Measure customer value
- Build an executive dashboard
- Provide business recommendations to reduce churn

**Key Business Questions**
1. What is the overall churn rate?
2. Which customer segments experience has the highest churn?
3. How does contract type influence customer churn?
4. How does customer tenure affect churn?
5. Which internet services and additional services are associated with higher churn?
6. Does payment method influence customer churn?
7. Which customer segments contribute the highest revenue and customer lifetime value (CLV)?
8. What business actions can reduce churn while maximizing customer value?

# Connect to GDrive
"""

from google.colab import drive
drive.mount ("/content/gdrive")

"""# Import Library"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

"""# Load Dataset"""

#Path definition
path ='/content/gdrive/MyDrive/Portfolio/Customer Churn/WA_Fn-UseC_-Telco-Customer-Churn.csv'

#Read the CSV file
df = pd.read_csv(path)
df.head()

df.info()

df.describe()

"""# Data Cleaning/Data Quality Check

## Missing Value
"""

missing = pd.DataFrame ({
    'total_missing': df.isnull().sum()
    })
missing

"""## Check Blank String"""

(df == " ").sum()

"""## Duplicate"""

df.duplicated().sum()

"""## Unique Value"""

unique=pd.DataFrame({
    'unique': df.nunique()
    })
unique

"""## Check Categorical Distribution"""

for col in df.select_dtypes(include='object'):
    print(df[col].value_counts())

"""## Convert Data Type"""

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
#df['Churn'] = df['Churn'].map({'Yes':1, 'No':0})

df.info()

"""# Feature Engineering"""

service_cols = [
    'PhoneService',
    'MultipleLines',
    'InternetService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies'
]

df['TotalServices'] = df[service_cols].apply(
    lambda x: sum(
        value in ['Yes', 'DSL', 'Fiber optic']
        for value in x
    ),
    axis=1
)
service_cols

"""## Monthly Revenue"""

df["MonthlyRevenue"] = df["MonthlyCharges"]
df.head()

"""## Customer Lifetime Value"""

df['CLV'] = df['MonthlyCharges'] * df['tenure']
df.head()

"""## Tenure Group"""

bins = [0,12,24,48,72]

labels = [
    "0-12 Months",
    "13-24 Months",
    "25-48 Months",
    "49-72 Months"
]

df["TenureGroup"] = pd.cut(
    df["tenure"],
    bins=bins,
    labels=labels,
    include_lowest=True
)
df.head()

"""# Feature Validation"""

df[['customerID',
    'tenure',
    'TenureGroup',
    'TotalServices',
    'MonthlyCharges',
    'CLV']].head()

"""# Save Data Clean"""

save_path="/content/gdrive/MyDrive/Portfolio/Customer Churn/telco_clean.csv"

df.to_csv(save_path,index=False)

"""# Exploratory Data Analysis (EDA)

## Executive KPI Overview

### Total Customer
"""

total_customer = df['customerID'].nunique()

print(f"Total Customers : {total_customer}")

"""### Churn Rate Distribution"""

churn_summary = (
    df['Churn']
    .value_counts()
    .reset_index()
)

churn_summary.columns = ['Churn','Customers']

churn_summary['Percentage'] = (
    churn_summary['Customers']
    / churn_summary['Customers'].sum()
    *100
).round(2)

churn_summary

"""### Total Monthly Revenue"""

df['MonthlyCharges'].sum()
print(f"Total Monthly Revenue : {df['MonthlyCharges'].sum()}")

"""### Average Monthly Revenue"""

df['MonthlyCharges'].mean()
print(f"Average Monthly Charge : {df['MonthlyCharges'].mean()}")

"""### Average Customer Lifetime Value"""

df['tenure'].mean()
print(f"Average Customer Lifetime : {df['tenure'].mean()}")

"""### Average Cust Lifetime Value"""

df['CLV'].mean()
print(f"Average Customer Lifetime Value : {df['CLV'].mean()}")

"""## Business Question

### Overall Customer Churn Rate
"""

churn_rate = (
    df['Churn']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

churn_rate

# Visualization

(
    df['Churn']
    .value_counts()
    .plot(kind='pie',
          autopct='%1.1f%%',
          ylabel='')
)

plt.title("Customer Churn Distribution")
plt.show()

"""Insight :
Around 26.6% of customers have churned, indicating that customer retention should become one of the company's strategic priorities.

###  Contract type with the highest churn
"""

contract_churn = pd.crosstab(
    df['Contract'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

contract_churn

# Visualisasi

contract_churn['Yes'].sort_values().plot(kind='barh')
plt.title("Churn Rate by Contract")
plt.xlabel("Churn Rate (%)")
plt.show()

"""Insight:
Customers on month-to-month contracts generally exhibit the highest churn rate compared with customers on longer-term contracts

### Internet Service with the Highest Churn
"""

internet_churn = pd.crosstab(
    df['InternetService'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

internet_churn

# Visualization

internet_churn['Yes'].plot(kind='bar')
plt.ylabel("Churn Rate")
plt.show()

"""Insight:
Compare churn rates across Fiber optic, DSL, and No Internet Service to identify the segment with the greatest retention challenge

### Tenure Affect Churn
"""

tenure_churn = pd.crosstab(
    df['TenureGroup'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

tenure_churn

# Visualization

tenure_churn['Yes'].plot(kind='bar')
plt.ylabel("Churn Rate")
plt.show()

"""Insight:
Customers with shorter tenure generally tend to churn more frequently than long-tenured customers.

### Payment method with the highest churn
"""

payment_churn = pd.crosstab(
    df['PaymentMethod'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

payment_churn

# Visualization

payment_churn['Yes'].sort_values().plot(kind='barh')
plt.show()

"""Insight :
Payment methods with relatively high churn may indicate customer friction or reflect characteristics of specific customer segments.

### Tech Support Reduce Churn?
"""

tech_support = pd.crosstab(
    df['TechSupport'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

tech_support

# Visualization

tech_support['Yes'].plot(kind='bar')
plt.show()

"""Insight:

Compare churn rates between customers with and without Tech Support to assess whether support services are associated with higher retention.

### Online Security reduce churn?
"""

security = pd.crosstab(
    df['OnlineSecurity'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

security

"""### Customer Segment that generate high revenue"""

revenue_contract = (
    df
    .groupby('Contract', as_index=False)
    ['MonthlyCharges']
    .sum()
    .sort_values('MonthlyCharges', ascending=False)
)

revenue_contract

# Visualization

plt.bar(
    revenue_contract['Contract'],
    revenue_contract['MonthlyCharges']
)

plt.title("Revenue by Contract")

plt.show()

"""Insight

Revenue contribution varies across contract types and should be evaluated alongside churn to prioritize high-value customer segments.

### Tenure group contributes the highest revenue
"""

revenue_tenure = (
    df
    .groupby('TenureGroup', as_index=False)
    ['MonthlyCharges']
    .sum()
)

revenue_tenure

"""### Total services does each customer subscribe"""

service_distribution = (
    df['TotalServices']
    .value_counts()
    .sort_index()
)

service_distribution

# Visualization

service_distribution.plot(kind='bar')

plt.title("Distribution of Total Services")

plt.show()

"""### number of subscribed services influence churn"""

service_churn = pd.crosstab(
    df['TotalServices'],
    df['Churn'],
    normalize='index'
).mul(100).round(2)

service_churn

# Visualization

service_churn['Yes'].plot(marker='o')

plt.ylabel("Churn Rate")

plt.show()

"""Insight

This analysis helps determine whether customers using more services are less likely to churn, indicating potential benefits of cross-selling.

### Customer profile has the highest churn
"""

profile = pd.pivot_table(
    df,
    values='customerID',
    index=['Contract','InternetService'],
    columns='Churn',
    aggfunc='count',
    fill_value=0
)

profile['Churn Rate (%)'] = (
    profile['Yes']
    /(profile['Yes']+profile['No'])
    *100
).round(2)

profile.sort_values(
    'Churn Rate (%)',
    ascending=False
)

"""# Business Impact Analysis

## Revenue at Risk
"""

churn_df = df[df['Churn']=='Yes']

revenue_at_risk = pd.DataFrame({
    'Metric':[
        'Total Churn Customers',
        'Monthly Revenue at Risk',
        'Average Monthly Revenue'
    ],
    'Value':[
        churn_df['customerID'].count(),
        churn_df['MonthlyCharges'].sum(),
        churn_df['MonthlyCharges'].mean()
    ]
})

revenue_at_risk

# Annual Projection

monthly_loss = df.loc[df['Churn']=="Yes","MonthlyCharges"].sum()

annual_loss = monthly_loss * 12

print(annual_loss)

"""Assuming churned customers are not replaced immediately, the company could potentially lose approximately X in annual recurring revenue.

## Revenue at Risk by Contract
"""

risk_contract = (
    df[df['Churn']=="Yes"]
    .groupby('Contract',as_index=False)
    .agg(
        Customers=('customerID','count'),
        Revenue_At_Risk=('MonthlyCharges','sum')
    )
    .sort_values(
        'Revenue_At_Risk',
        ascending=False
    )
)

risk_contract

"""## Revenue at Risk by Internet Service"""

risk_internet = (
    df[df['Churn']=="Yes"]
    .groupby('InternetService',as_index=False)
    .agg(
        Customers=('customerID','count'),
        Revenue_At_Risk=('MonthlyCharges','sum')
    )
    .sort_values(
        'Revenue_At_Risk',
        ascending=False
    )
)
risk_internet

"""## High Value Customer at Risk"""

clv_threshold = df['CLV'].median()

high_value_risk = df[
    (df['CLV']>=clv_threshold)
    &
    (df['Churn']=="Yes")
]

high_value_risk.head()

high_value_summary = pd.DataFrame({
    'Metric':[
        'High Value Customers',
        'Monthly Revenue at Risk',
        'Average CLV'
    ],
    'Value':[
        high_value_risk['customerID'].count(),
        high_value_risk['MonthlyCharges'].sum(),
        high_value_risk['CLV'].mean()
    ]
})

high_value_summary

"""## Customer Risk Segmentation"""

clv_median = df['CLV'].median()

def risk_segment(row):

    if row['Contract']=="Month-to-month" and row['CLV']>=clv_median:
        return "High Risk - High Value"

    elif row['Contract']=="Month-to-month":
        return "High Risk"

    elif row['CLV']>=clv_median:
        return "High Value"

    else:
        return "Low Risk"

df['RiskSegment']=df.apply(
    risk_segment,
    axis=1
)

risk_summary = (
    df
    .groupby('RiskSegment')
    .agg(
        Customers=('customerID','count'),
        Revenue=('MonthlyCharges','sum'),
        AvgCLV=('CLV','mean')
    )
)

risk_summary

"""# Executive Summary

The overall churn rate is 26.58%, indicating that approximately one in four customers discontinued the service.
Customers on month-to-month contracts experience substantially higher churn than those on annual or two-year contracts.
Churn patterns vary by Internet Service and Payment Method, suggesting that service experience and billing preferences may influence customer retention.
Customers with shorter tenure are more likely to churn, highlighting the importance of effective onboarding and early engagement.
Customers subscribed to Tech Support and Online Security generally demonstrate better retention, presenting opportunities for cross-selling value-added services.
Combining churn risk with revenue contribution enables the business to prioritize retention initiatives for high-value customer segments.

# Key Findings

1. Customer Churn Remains a Significant Business Issue
Approximately one-quarter of the customer base has discontinued the service, representing a substantial risk to recurring revenue and long-term business growth.
Business Impact
Loss of recurring subscription revenue
Higher customer acquisition costs
Reduced customer lifetime value
2. Contract Type Is the Strongest Indicator of Customer Retention
Customers subscribed to month-to-month contracts demonstrate considerably higher churn rates than those committed to one-year or two-year contracts.
Business Interpretation
Long-term contractual commitments contribute to greater customer loyalty and lower attrition.
3. Early Lifecycle Customers Are More Likely to Churn
Customers with shorter tenure consistently exhibit higher churn rates compared with long-tenured customers.
Business Interpretation
The first year of the customer lifecycle represents the highest-risk period and should become the primary focus of retention efforts.
4. Value-Added Services Are Associated with Better Customer Retention
Customers who subscribe to additional services such as Tech Support and Online Security generally experience lower churn compared with customers who do not.
Business Interpretation
Customers who perceive greater service value tend to remain with the company longer.
5. Revenue Contribution Is Uneven Across Customer Segments
Revenue is concentrated within specific customer groups. Evaluating churn together with customer value enables the business to identify high-value customers who should be prioritized for retention campaigns.
6. Customer Characteristics Influence Churn Behavior
Customer demographics alone provide limited explanatory power. Instead, churn appears to be more closely associated with customer experience, service utilization, and subscription behavior.

# Recommendation

1. Strengthen Early Customer Retention Programs

Objective

Reduce churn among newly acquired customers.

Recommended Actions

- Launch onboarding campaigns during the first 90 days.
- Conduct proactive follow-up calls or emails for new customers.
- Provide educational content highlighting available services and product benefits.
- Offer introductory incentives to encourage long-term engagement.

Expected Business Outcome

- Improved customer satisfaction
- Reduced early-stage churn
- Increased customer lifetime value

2. Encourage Migration to Long-Term Contracts

Objective

Increase customer retention by promoting longer subscription commitments.

Recommended Actions

- Provide discounts for annual contracts.
- Introduce loyalty rewards for contract renewals.
- Offer bundled packages exclusively for long-term subscribers.

Expected Business Outcome

- Higher customer retention
- More predictable recurring revenue
- Lower acquisition costs

3. Increase Adoption of Value-Added Services

Objective

Improve customer stickiness through additional service offerings.

Recommended Actions

- Bundle Tech Support with premium internet packages.
- Promote Online Security as an essential service.
- Create personalized cross-selling campaigns based on customer profiles.

Expected Business Outcome

- Higher average revenue per customer
- Lower churn probability
- Increased perceived service value

4. Develop a Churn Risk Monitoring Dashboard

Objective

Enable proactive intervention before customers decide to leave.

Recommended Actions

Monitor customers with characteristics such as:
- Month-to-month contracts
- Short tenure
- Limited subscribed services
- High monthly charges
- Recent service changes

Expected Business Outcome

- Earlier identification of high-risk customers
- More effective retention campaigns
- Better allocation of customer success resources

5. Prioritize High-Value Customer Retention

Objective

Protect customers contributing the highest business value.

Recommended Actions

Segment customers based on:
- Customer Lifetime Value (CLV)
- Monthly Revenue
- Contract Type
- Churn Risk
Provide exclusive retention programs for customers combining high value and high churn risk.

Expected Business Outcome

- Reduced revenue loss
- Improved profitability
- Increased customer lifetime value

# Business Conclusion

This analysis demonstrates that customer churn is influenced primarily by customer engagement and subscription behavior rather than demographic characteristics. Customers with shorter tenure, flexible contracts, and fewer subscribed services consistently exhibit higher churn risk.
By combining customer segmentation, churn analysis, and revenue metrics into a unified executive dashboard, management can proactively identify high-risk customer groups and implement targeted retention strategies. These insights support data-driven decision making and help maximize long-term customer value while reducing revenue leakage.

# Potential Business Impact

| Recommendation                     | Expected KPI Impact                                              |
| ---------------------------------- | ---------------------------------------------------------------- |
| Early Retention Program            | Lower churn rate among new customers                             |
| Long-Term Contract Campaign        | Higher contract renewal rate                                     |
| Cross-Selling Value-Added Services | Higher Average Revenue per User (ARPU)                           |
| Churn Monitoring Dashboard         | Faster identification of at-risk customers                       |
| High-Value Customer Retention      | Increased Customer Lifetime Value (CLV) and reduced revenue loss |
"""